name: Restart Codespace

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Wake Codespace
        run: |
          echo "Checking codespace..."
